### ISSUE TITLE
Memory requirements

### ISSUE THREAD

**Issue by varun19299** [dasongli1/Shift-Net#1]
How much memory (and what GPU specs) is needed for training the small model (Ours-s in the main paper)?

Thanks!

**Comment by dasongli1** [comment]
Training the small model requires 8 * 32G V100 gpu. But you can change n_sequence in yml for other memories. 
Changing the PyTorch version to 2.0 may also reduce memory cost.

**Comment by varun19299** [comment]
Thank you for your reply!

A few more questions:

* does the code base incorporate mixed precision or half precision training?

* what were the sequence lengths and the batch sizes attained when using 8 GPUs with 32 GB VRAM each?
