### ISSUE TITLE
`default_init_weights` not defined

### ISSUE THREAD

**Issue by varun19299** [dasongli1/Shift-Net#2]
The function default_init_weights  seems to be missing from `basicsr/models/archs`

Is this the same as the one used in EDVR? https://github.com/xinntao/EDVR/blob/b02e63a0fc5854cad7b11a87f74601612e356eff/basicsr/models/archs/arch_util.py#L21

**Comment by dasongli1** [comment]
The function ``` default_init_weights``` is not called.  ```self.init_weights()``` is commented.
